SOCIAL BLOG/socialcompanyblog/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class BlogPostForm(FlaskForm):
	title = StringField('Title', validators = [DataRequired()])
	text = TextAreaField('Text', validators = [DataRequired()])
	submit = SubmitField("Post")
	

SOCIAL BLOG/socialcompanyblog/blog_posts/views.py
from flask import render_template, redirect, url_for, Flask, request, Blueprint,flash
from flask_login import current_user, login_required
from socialcompanyblog import db
from socialcompanyblog.models import BlogPost
from socialcompanyblog.blog_posts.forms import BlogPostForm 

blog_posts = Blueprint('blog_posts',__name__)


#CREATE

@blog_posts.route('/create', methods = ['GET','POST'])
@login_required
def create_post():
	form = BlogPostForm()

	if form.validate_on_submit():

		blog_post = BlogPost(title = form.title.data,
							 text = form.text.data, 
							 user_id = current_user.id)
		db.session.add(blog_post)
		db.session.commit()
		flash('Blog Post Created')
		return redirect(url_for('core.index'))
	return render_template('create_post.html', form = form)

#VIEW

@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
	blog_post = BlogPost.query.get_or_404(blog_post_id)
	return render_template('blog_post.html', title = blog_post.title,
							date = blog_post.date, post = blog_post)

#UPDATE

@blog_posts.route('/<int:blog_post_id>/update', methods = ['GET', 'POST'])
@login_required
def update(blog_post_id):
	blog_post = BlogPost.query.get_or_404(blog_post_id)

	if blog_post.author != current_user:
		abort(403)

	form = BlogPostForm()
	if form.validate_on_submit():

		blog_post.title = form.title.data
		blog_post.text = form.text.data
		
		db.session.commit()
		flash('Blog Post Updated')
		return redirect(url_for('blog_posts.blog_post', blog_post_id = blog_post.id))

	elif request.method == 'GET':
		form.title.data = blog_post.title
		form.text.data = blog_post.text

	return render_template('create_post.html',title = "Updating", form = form)

#DELETE

@blog_posts.route('/<int:blog_post_id>/delete', methods = ['GET', 'POST'])
@login_required
def delete_post(blog_post_id):
	blog_post = BlogPost.query.get_or_404(blog_post_id)

	if blog_post.author != current_user:
		abort(403)

	db.session.delete(blog_post)
	db.session.commit()
	flash('Blog Post Deleted')

	return redirect(url_for('core.index'))
	



SOCIAL BLOG/socialcompanyblog/core/views.py
#core/view.py

from socialcompanyblog.models import BlogPost
from flask import render_template, request, Blueprint

core = Blueprint('core',__name__)

@core.route('/')
def index():
	page = request.args.get('page', 1, type = int)
	blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page = page, per_page = 5)

	return render_template('index.html', blog_posts = blog_posts)

@core.route('/info')
def info():
	return render_template('info.html')




SOCIAL BLOG/socialcompanyblog/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from socialcompanyblog import db
from werkzeug.security import generate_password_hash,check_password_hash
from socialcompanyblog.models import User, BlogPost
from socialcompanyblog.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from socialcompanyblog.users.picture_handler import add_profile_pic


users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering! Now you can login!')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():
        # Grab the user from our User Models table
        user = User.query.filter_by(email=form.email.data).first()

        # Check that the user was supplied and the password is right
        # The verify_password method comes from the User object
        # https://stackoverflow.com/questions/2209755/python-operation-vs-is-not

        if user.check_password(form.password.data) and user is not None:
            #Log in the user

            login_user(user)
            flash('Logged in successfully.')

            # If a user was trying to visit a page that requires a login
            # flask saves that URL as 'next'.
            next = request.args.get('next')

            # So let's now check if that next exists, otherwise we'll go to
            # the welcome page.
            if next == None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)
    return render_template('login.html', form=form)




@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('core.index'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():

    form = UpdateUserForm()

    if form.validate_on_submit():
        print(form)
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)


@users.route("/<username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)
    return render_template('user_blog_posts.html', blog_posts=blog_posts, user=user)


SOCIAL BLOG/socialcompanyblog/templates/account.html
{% extends "base.html" %}
{% block content %}

<style>
		body{
			background-image: url("https://images.unsplash.com/photo-1514064019862-23e2a332a6a6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=916&q=80");
			background-repeat: no-repeat;
			background-size: 100% 100%;
		}

    .jumbotron{
      padding-bottom: 10px;
      padding-top: 10px;
    }
	</style>



<div class = "jumbotron">
	<div align = "center">
		<h1 style="font-family: sans-serif;">Welcome to the page for {{current_user.username}}</h1>
		<img  align= 'center' src = "{{url_for('static', filename ='profile_pics/'+ current_user.profile_image)}}">
	</div>
</div>


<div class = "container">
	<form method = "POST" action = "" enctype="multipart/form-data" style="border-radius: 10px; border:1px solid black; padding:20px; align-content: center; z-index: 1; " class="p-3 mb-2 bg-dark text-white">
		{{form.hidden_tag()}}

		<div class ="form-group"> 
			{{form.username.label(class = "form-group")}}	{{form.username(class = 'form-control')}} <br>
		</div>

		<div class ="form-group">
			{{form.email.label(class = "form-group")}}	{{form.email(class = 'form-control')}} <br>
		</div>

		<div class ="form-group">
			{{form.picture.label(class = "form-group")}}	{{form.picture(class = 'form-control')}} <br>
		</div>

		
		<div class ="form-group">
			{{form.submit(class = 'btn btn-primary')}}
		</div>
		
	</form>
</div>
{% endblock %}

SOCIAL BLOG/socialcompanyblog/templates/base.html
<!DOCTYPE html>
<html lang = "en" dir = "ltr">

	<head>

		<title></title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		<meta charset="utf-8">

	</head>

	<body>
		<!-- <nav class = "navbar navbar-dark bg-dark">
			<div class="collapse navbar-collapse" id="navbarSupportedContent">

			<ul class = "navbar-nav mr auto">

				<li class = 'nav-link'>
					<a href = "{{url_for('core.index')}}">Home</a>
				</li>

				<li class = 'nav-link'>
					<a href = "{{url_for('core.info')}}">About</a>
				</li>

				<li class = 'nav-link'>
					<a href = "#">Log Out</a>
				</li>

				<li class = 'nav-link'>
					<a href = "#">Account</a>
				</li>

				<li class = 'nav-link'>
					<a href = "#">Create Post</a>
				</li>

				<li class = 'nav-link'>
					<a href = "#">Log In</a>
				</li>

				<li class = 'nav-link'>
					<a href = "#">Register</a>
				</li>
			</ul>
		</div>

		</nav> -->

		<nav class = "navbar navbar-expand-lg navbar-dark bg-dark">
			<div class = "navbar-nav">
				<a class = "nav-item nav-link" href = "{{url_for('core.index')}}">Home</a>
				<a class = "nav-item nav-link" href = "{{url_for('core.info')}}">About</a>

				{% if current_user.is_authenticated %}
				<a class = "nav-item nav-link" href = "{{url_for('users.logout')}}">Log Out</a>
				<a class = "nav-item nav-link" href = "{{url_for('users.account')}}">Account</a>
				<a class = "nav-item nav-link" href = "{{url_for('blog_posts.create_post')}}">Create Post</a>

				{% else %}
				<a class = "nav-item nav-link" href = "{{url_for('users.login')}}">Log In</a>
				<a class = "nav-item nav-link" href = "{{url_for('users.register')}}">Register</a>

				{% endif %}
			</div>
		</nav>

		<div class = "container">

			{% block content %}

			{% endblock %}

		</div>

	</body>

</html>

SOCIAL BLOG/socialcompanyblog/templates/blog_post.html
{% extends "base.html" %}
{% block content %}


<style>
         body{
      background-image: url("https://images.unsplash.com/photo-1514064019862-23e2a332a6a6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=916&q=80");
      background-repeat: no-repeat;
      background-size: 100% 100%;
    }

    html {
        height: 100%
    }
  </style>



<br><br>
<div class = "jumbotron p-3 mb-2 bg-light text-dark">

	<h1 >{{post.title}}</h1>
	<h2>Written by : {{post.author.username}}</h2>
	<h3>Published : {{post.date.strftime('%B %d, %Y')}}</h3>
	<p>{{post.text}}</p>

	{% if post.author == current_user %}

	<div>
		<a href = "{{url_for('blog_posts.update',blog_post_id = post.id)}}">Update</a>
		<button type = "button" class = "btn btn-danger" data-toggle = 'modal' data-target = "#del_modal">Delete</button>

	</div>

	{% endif %}
</div>


<div class="modal" tabindex="-1" role="dialog" id="del_modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete Post?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete the post?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

        <form action = "{{url_for('blog_posts.delete_post',blog_post_id = post.id)}}" method = "POST">
        	<input class ="btn btn-danger" type = "submit"  value = "Delete">
        </form>
      </div>
    </div>
  </div>
</div>















{% endblock %}

SOCIAL BLOG/socialcompanyblog/templates/create_post.html
{% extends "base.html" %}
{% block content %}


<style>
		body{
			background-image: url("https://images.unsplash.com/photo-1514064019862-23e2a332a6a6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=916&q=80");
			background-repeat: no-repeat;
			background-size: 100% 100%;
		}


		html {
    		height: 100%
		}
</style>
<br><br><br>
<div class = "container">
	<form  method = "POST"  class="p-3 mb-2 bg-dark text-white">
		{{form.hidden_tag()}}

		<div class = "form-group">
			{{form.title.label(class = "form-control-label")}}
			{{form.title(class = "form-control form-control-lg")}}
		</div>

		<div class = "form-group">
			{{form.text.label(class = "form-control-label")}}
			{{form.text(class = "form-control form-control-lg")}}
		</div>

		<div class = "form-group">
			{{form.submit(class="btn btn-success")}}
		</div>

	</form>
</div>

{% endblock %}

<!-- class = "form-group" -->

SOCIAL BLOG/socialcompanyblog/templates/index.html
{% extends "base.html" %}
{% block content %}

	<style>
         body{
			background-image: url("https://images.unsplash.com/photo-1514064019862-23e2a332a6a6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=916&q=80");
			background-repeat: no-repeat;
			background-size: 100% 100%;
		}

		a:link { text-decoration: none}

		/*html {
    		height: 100%
		}*/
		.jumbotron{
			padding-bottom: 10px;
		}
	</style>

	<div class = "jumbotron ">
		<h1  class="display-4" style="text-align: center;">Social Company Blog</h1>
		<p style="font-size: 25px; text-align: center;">Keep connecting, keep sharing!</p>
	</div>

	<div class="container">

		{% for post in blog_posts.items %}
			<div class ="card">
				<div class = "card-body">
					<h2 class="text-info"><a class = "card-title" href = "{{url_for('blog_posts.blog_post', blog_post_id = post.id)}}">{{post.title}}</a></h2>

					<a style="text-decoration: none"  href = "{{url_for('users.user_posts', username = post.author.username )}}">Written by : {{post.author.username}}</a>

					<p>Published on: {{post.date.strftime('%d-%m-%Y')}}</p>

					<a class="btn btn-warning" href = "{{url_for('blog_posts.blog_post', blog_post_id = post.id)}}">Read blog post</a>

				</div>

				</div>
				<br>
				<br>
			{% endfor %}
			
			

	 	

	<nav aria-label="Page navigation example">
  		<ul class="pagination justify-content-center">
  			{% for page_num in blog_posts.iter_pages(left_edge=1, right_edge = 1, left_current = 1, right_current = 2) %}
  				{% if blog_posts.page == page_num %}
    			<li class="page-item disabled">
    				<a class="page-link" href="{{url_for('core.index', page = page_num)}}">{{page_num}}</a>
    			</li>
    			{% else %}
    			<li class="page-item">
    				<a class="page-link" href="{{url_for('core.index', page = page_num)}}">{{page_num}}</a>
    			</li>
    			{% endif %}
    		{% endfor %}
  		</ul>
	</nav>

	</div>
	
{% endblock %}



SOCIAL BLOG/socialcompanyblog/templates/info.html


{% extends "base.html" %}
{% block content %}

	<style>
		body{
			background-image: url("https://images.unsplash.com/photo-1514064019862-23e2a332a6a6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=916&q=80");
			background-repeat: no-repeat;
			background-size: 100% 100%;
		}

    .jumbotron{
      padding-bottom: 10px;
      padding-top: 10px;
    }
	</style>

	<div class = "jumbotron ">
		<h1  class="display-4" style="text-align: center;">About the company </h1><br>
		<p style="text-align: justify; ;">Welcome to the Social Company Blog! Join in with the others in sharing what you feel is important. Meet like-minded people and stumble upon creativity you've never seen before. Experience the new way of conneectivity and help keep yourself updated on the people who care about. Plus, it's free! Happy sharing :)</p>
	</div>

	

	<div class="container">
 		 <div class="row" style="padding-left: 35px">
    		<div class="col-sm">
      			<div class="card" style="width: 18rem;">
  				<img src="https://images.unsplash.com/photo-1535013113415-b315146c67d5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80" class="card-img-top" alt="...">
  					<div class="card-body">
    					<h5 class="card-title">Discover</h5>
    					<p class="card-text">Discover the knowledge that's been waiting on you to be gained.</p>
  					</div>
				</div>
    		</div>

    		<div class="col-sm">
      			<div class="card" style="width: 18rem;">
  					<img src="https://images.unsplash.com/photo-1493514789931-586cb221d7a7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1051&q=80" class="card-img-top" alt="...">
  						<div class="card-body">
    						<h5 class="card-title">Connect</h5>
    						<p class="card-text">Connect with the people you care about!</p>
  						</div>
				</div>
    		</div>

    		<div class="col-sm">
      			<div class="card" style="width: 18rem;">
  					<img src="https://images.unsplash.com/photo-1461696114087-397271a7aedc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80" class="card-img-top" alt="...">
  						<div class="card-body">
    						<h5 class="card-title">Free</h5>
    						<p class="card-text">Enjoy using our services cause it's totally free! </p>
  						</div>
				</div>
    		</div>
  		</div>
	</div>
	<br>

	

{% endblock %}

SOCIAL BLOG/socialcompanyblog/templates/login.html
{% extends "base.html" %}
{% block content %}

	<style>
         body{
			background-image: url("https://images.unsplash.com/photo-1514064019862-23e2a332a6a6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=916&q=80");
			background-repeat: no-repeat;
			background-size: 100% 100%;
		}

		html {
    		height: 100%
		}
	</style>


	<br><br><br>
	<h3 style="text-align: center; color: whitesmoke">Log in</h3>
		<form method="POST" style="border-radius: 10px; border:1px solid black;" class="p-3 mb-2 bg-dark text-white">

	<div class="form-group" class="p-3 mb-2 bg-gradient-dark text-white">
    	{# This hidden_tag is a CSRF security feature. #}
	    {{ form.hidden_tag() }}

	    <div class = "col-xs-4">
	    {{ form.email.label }} {{ form.email(class="form-control") }}<br>
		</div>

		<div class = "col-xs-4">
	    {{ form.password.label }} {{ form.password(class="form-control") }}<br>
		</div>
	    {{ form.submit(class="btn btn-primary") }}
	</div>

</form>

{% endblock %}



SOCIAL BLOG/socialcompanyblog/templates/register.html
{% extends "base.html" %}
{% block content %}

	<style>
         body{
			background-image: url("https://images.unsplash.com/photo-1514064019862-23e2a332a6a6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=916&q=80");
			background-repeat: no-repeat;
			background-size: 100% 100%;
		}
		ht/*ml {
    		height: 100%
		}*/
	</style>
	
	<!-- <h1 style="text-align: center; font-family: sans-serif; color: white">Register today!</h1> -->
	<br>
	<form method="POST" style="border-radius: 10px; border:1px solid black; padding:20px; align-content: center; z-index: 1; " class="p-3 mb-2 bg-dark text-white" >
		<div class="form-group" class="p-3 mb-2 bg-gradient-dark text-white">
		{{form.hidden_tag()}}
		<div class = "col-xs-4">
		{{form.email.label}}	{{form.email(class="form-control")}} <br>
		</div>

		<div class = "col-xs-4">
		{{form.username.label}}	{{form.username(class="form-control")}} <br>
		</div>

		<div class = "col-xs-3">
		{{form.password.label}}	{{form.password(class="form-control")}} <br>
		</div>

		<div class = "col-xs-4">
		{{form.pass_confirm.label}}	{{form.pass_confirm(class="form-control")}} <br>
		</div>
	</div>
		{{form.submit(class="btn btn-primary")}}
	</form>
	<br>


{% endblock %}



SOCIAL BLOG/socialcompanyblog/templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}

<style type="text/css">
  body{
      background-image: url("https://images.unsplash.com/photo-1514064019862-23e2a332a6a6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=916&q=80");
      background-repeat: no-repeat;
      background-size: 100% 100%;
    }

    /*html {
        height: 100%
    }*/
  a:link { text-decoration: none}

</style>

<div class="container">
  <div class="jumbotron">
    <div align='center'>
      <h1 >Welcome to the page for {{user.username}}</h1>
      <img align='center' src="{{ url_for('static', filename='profile_pics/' + user.profile_image) }}">
    </div>
  </div>


{% for post in blog_posts.items %}
<div class ="card p-3 mb-2 bg-light text-dark">
  <div class = "card-body">

          <h2><a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
          Written by: <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
          <p class="text-muted">Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
          <br>
            <p>{{post.text}}</p>
          <br>
        </div>
      </div>

{% endfor %}


</div>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {# http://flask.pocoo.org/snippets/44/ #}

    {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if blog_posts.page == page_num %}
              <li class="page-item disabled">
                <a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
              </li>
            {% else %}
              <li class="page-item"><a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
            {% endif %}
    {% endfor %}
</nav>
{% endblock content %}